# Generated by Django 5.2 on 2025-04-25 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Финансовый профиль',
                'verbose_name_plural': 'Финансовые профили',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('increase_period', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('accrual_type', models.CharField(choices=[('RC', 'Рекуррентное пополнение (низкий % каждый период)'), ('OT', 'Одноразовое пополнение (высокий % первый период)')], default='RC', max_length=2)),
                ('is_increasable_all_time', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='finance.financialprofile')),
            ],
            options={
                'verbose_name': 'Депозит',
                'verbose_name_plural': 'Депозиты',
            },
        ),
    ]
