# Generated by Django 5.2 on 2025-04-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='is_increasable_all_time',
        ),
    ]
