# Generated by Django 5.2 on 2025-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_deposit_is_increasable_all_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='date_when_increase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
