# Generated by Django 5.2 on 2025-04-28 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_deposit_date_when_increase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='savings_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accrual_type', models.CharField(choices=[('RC', 'Рекуррентное пополнение (низкий % каждый период)'), ('OT', 'Одноразовое пополнение (высокий % первый период)')], default='RC', max_length=2)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term_months', models.PositiveIntegerField(blank=True, help_text='Если указано — число месяцев до окончания вклада', null=True)),
                ('replenishable', models.BooleanField(default=True, help_text='Можно ли пополнять каждый месяц (True) или нет (False)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сбережения',
                'verbose_name_plural': 'Сбережения',
            },
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
