# Generated by Django 5.2 on 2025-04-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_financialprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialprofile',
            name='savings_rate',
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
