# Generated by Django 5.2 on 2025-04-29 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_financialprofile_savings_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Процент откладываемых денег от зарплаты, не обязательный параметр', max_digits=10),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accrual_type', models.CharField(choices=[('RC', 'Рекуррентное пополнение (низкий % каждый период)'), ('OT', 'Одноразовое пополнение (высокий % первый период)')], default='RC', max_length=2)),
                ('start_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term_months', models.PositiveIntegerField(blank=True, help_text='Если указано — число месяцев до окончания вклада', null=True)),
                ('replenishable', models.BooleanField(default=True, help_text='Можно ли пополнять каждый месяц (True) или нет (False)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вклад',
                'verbose_name_plural': 'Вклады',
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('INTEREST', 'Начисление процентов'), ('MANUAL', 'Ручное пополнение')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.deposit')),
            ],
            options={
                'verbose_name': 'Транзакция по вкладу',
                'verbose_name_plural': 'Транзакции по вкладу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SavingsGoal',
        ),
    ]
