# Generated by Django 5.2 on 2025-04-29 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_financialprofile_monthly_savings_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='accrual_frequency',
            field=models.PositiveIntegerField(default=30, help_text='Если указано — частота начисления процентов (в днях)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='start_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Процент откладываемых денег от зарплаты, не обязательный параметр', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
