# Generated by Django 5.2 on 2025-05-01 14:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_deposit_accrual_frequency_alter_deposit_deposit_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='term_months',
            field=models.PositiveIntegerField(blank=True, help_text='Если указано — число месяцев до окончания вклада', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.deposit'),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='type',
            field=models.CharField(choices=[('CONTRIBUTION', 'Пополнение'), ('INTEREST', 'Начисление процентов')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма откладываемых денег за каждый период начисления процентов', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
