# Generated by Django 5.2 on 2025-05-01 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_deposittransaction_balance_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
