# Generated by Django 5.2 on 2025-05-06 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_deposittransaction_balance_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма откладываемых денег за каждый период начисления процентов если позволяет депозит', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
