# Generated by Django 5.2 on 2025-06-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userboost_userinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='donation_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
