# Generated by Django 5.2 on 2025-06-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userboost_user_userstreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstreak',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
