# Generated by Django 5.2 on 2025-08-02 18:20

import core.accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_achievement_userachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_offer', models.JSONField(default=dict, help_text='Trade offer | Example: {"xp": 100, "coins": 100, "items_ids": [1, 2, 3]}', validators=[core.accounts.validators.validate_trade_offer])),
                ('recipient_offer', models.JSONField(default=dict, help_text='Trade offer | Example: {"xp": 100, "coins": 100, "items_ids": [1, 2, 3]}', validators=[core.accounts.validators.validate_trade_offer])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_trades', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обмен',
                'verbose_name_plural': 'Обмены',
                'ordering': ['-created_at'],
            },
        ),
    ]
