# Generated by Django 5.2 on 2025-08-10 08:56

import core.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='recipient_offer',
            field=models.JSONField(default=dict, help_text='Trade offer | Example: {"coins": 100, "items_ids": [1, 2, 3]}', validators=[core.accounts.validators.validate_trade_offer]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='requester_offer',
            field=models.JSONField(default=dict, help_text='Trade offer | Example: {"coins": 100, "items_ids": [1, 2, 3]}', validators=[core.accounts.validators.validate_trade_offer]),
        ),
    ]
