# Generated by Django 5.2 on 2025-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
