# Generated by Django 5.2 on 2025-06-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_updated_at_todo_executed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_dream_step',
            field=models.BooleanField(default=False),
        ),
    ]
