# Generated by Django 5.2 on 2025-07-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0002_dreamimage_is_preview'),
        ('todo', '0003_todo_is_dream_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dream.dream'),
        ),
    ]
