# Generated by Django 5.2 on 2025-09-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_golden',
            field=models.BooleanField(default=False),
        ),
    ]
