# Generated by Django 5.2 on 2025-06-14 07:46

import core.shop.interfaces
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='shop_items/')),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('background', 'Background'), ('avatar', 'Avatar'), ('icon', 'Icon'), ('boost', 'Boost')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvatarItem',
            fields=[
                ('baseshopitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseshopitem')),
            ],
            bases=('shop.baseshopitem', core.shop.interfaces.SaveableItemMixin, core.shop.interfaces.ApplicableItemMixin),
        ),
        migrations.CreateModel(
            name='BackgroundItem',
            fields=[
                ('baseshopitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseshopitem')),
            ],
            bases=('shop.baseshopitem', core.shop.interfaces.SaveableItemMixin, core.shop.interfaces.ApplicableItemMixin),
        ),
        migrations.CreateModel(
            name='BoostItem',
            fields=[
                ('baseshopitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseshopitem')),
                ('boost_type', models.CharField(choices=[('xp', 'Xp'), ('money', 'Money')], max_length=20)),
                ('multiplier', models.FloatField(default=1.5)),
                ('duration_minutes', models.PositiveIntegerField()),
            ],
            bases=('shop.baseshopitem', core.shop.interfaces.SaveableItemMixin, core.shop.interfaces.ApplicableItemMixin),
        ),
        migrations.CreateModel(
            name='IconItem',
            fields=[
                ('baseshopitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseshopitem')),
            ],
            bases=('shop.baseshopitem', core.shop.interfaces.SaveableItemMixin, core.shop.interfaces.ApplicableItemMixin),
        ),
    ]
