# Generated by Django 5.2 on 2025-06-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseshopitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
