# Generated by Django 5.2 on 2025-06-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_baseshopitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseshopitem',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
    ]
