# Generated by Django 5.2 on 2025-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='habits_completed',
            field=models.IntegerField(default=0),
        ),
    ]
