# Generated by Django 5.2 on 2025-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamimage',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
